import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Chakra_Providers } from "./ui/chakraProvider/page";
import { React_Query_Provider } from "./ui/reactQueryProvider/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Chakra_Providers>
        <body className={inter.className}>
          <React_Query_Provider>{children}</React_Query_Provider>
        </body>
      </Chakra_Providers>
    </html>
  );
}
